#!/usr/bin/env python3
import json, os

def r(*turns):
    msgs = []
    for i, t in enumerate(turns):
        msgs.append({"role": "user" if i % 2 == 0 else "assistant", "content": t})
    return {"messages": msgs}

records = [

# ========== GRUP A – 2 tur: sipariş → hepsi bu (50) ==========

r("Bana bir mercimek çorbası.",
  "Memnuniyetle, Mercimek Çorbası 85 TL. Başka bir arzunuz var mı?",
  "Hayır, hepsi bu.",
  "Hemen hazırlıyorum efendim, afiyet olsun."),

r("Bir kremalı mantar çorbası alayım.",
  "Tabii, Kremalı Mantar Çorbası 95 TL. Ekleyeceğimiz bir şey var mı?",
  "Teşekkürler, şimdilik bu kadar.",
  "Siparişinizi hemen mutfağa iletiyorum, iyi günler."),

r("Bir porsiyon ızgara köfte.",
  "Elbette, Izgara Köfte 240 TL. Başka bir isteğiniz var mı?",
  "Yeter bu kadar.",
  "Birazdan masanıza getiriyorum efendim, afiyet olsun."),

r("Et döner verir misiniz?",
  "Memnuniyetle, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Hayır, teşekkür ederim.",
  "Hemen hazırlatıyorum, kısa sürede masanızda olacak."),

r("Tavuk salata rica ediyorum.",
  "Tabii, Izgara Tavuk Salata 210 TL. İlaveten bir arzunuz olur mu?",
  "Yok, hepsi bu kadar.",
  "Siparişinizi hızla hazırlıyorum efendim."),

r("Bir fırın sütlaç olsun.",
  "Elbette, Fırın Sütlaç 100 TL. Eklemek istediğiniz bir şey var mı?",
  "Teşekkürler, yeterli.",
  "Hemen getiriyorum efendim, afiyet olsun."),

r("Bize bir künefe.",
  "Memnuniyetle, Künefe 140 TL. Başka bir arzunuz var mı?",
  "Şimdilik başka bir şey istemiyorum.",
  "Kısa sürede masanıza servis ediyorum efendim."),

r("Bir yayık ayran alayım.",
  "Tabii, Yayık Ayran 45 TL. Başka bir isteğiniz var mı?",
  "Hayır, hepsi bu.",
  "Hemen getiriyorum, iyi günler dileriz."),

r("Limonata siparişi vereyim.",
  "Elbette, Limonata 70 TL. Ekleyeceğimiz bir şey var mı?",
  "Teşekkürler, bu kadar.",
  "Hemen masanıza yönlendiriyorum efendim."),

r("Şalgam suyu rica ediyorum.",
  "Memnuniyetle, Şalgam Suyu 50 TL. Başka bir arzunuz var mı?",
  "Yok, yeterli.",
  "Birazdan servis ediyorum efendim, afiyet olsun."),

r("İki mercimek çorbası.",
  "Tabii, 2 Mercimek Çorbası 170 TL. İlaveten bir arzunuz olur mu?",
  "Hayır, hepsi bu kadar.",
  "Hemen hazırlatıyorum efendim."),

r("İki mantar çorbası alalım.",
  "Elbette, 2 Kremalı Mantar Çorbası 190 TL. Başka bir isteğiniz var mı?",
  "Teşekkür ederim, yeter.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("Bize iki köfte.",
  "Memnuniyetle, 2 Izgara Köfte 480 TL. Eklemek istediğiniz bir şey var mı?",
  "Hayır, şimdilik hepsi bu.",
  "Hemen hazırlıyorum, kısa sürede masanızda olacak."),

r("İki et döner verir misiniz?",
  "Tabii, 2 Et Döner 560 TL. Başka bir arzunuz var mı?",
  "Yok, teşekkürler.",
  "Birazdan servis ediyorum efendim, afiyet olsun."),

r("İki salata olsun.",
  "Elbette, 2 Izgara Tavuk Salata 420 TL. Ekleyeceğimiz bir şey var mı?",
  "Yeterli, hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("Üç sütlaç rica ediyorum.",
  "Memnuniyetle, 3 Fırın Sütlaç 300 TL. Başka bir arzunuz var mı?",
  "Teşekkürler, başka bir şey yok.",
  "Kısa sürede tatlılarınızı getiriyorum efendim."),

r("Üç künefe alalım.",
  "Tabii, 3 Künefe 420 TL. Başka bir isteğiniz var mı?",
  "Hayır, yeterli.",
  "Sıcak sıcak hemen masanıza getiriyorum."),

r("Üç ayran verir misiniz?",
  "Elbette, 3 Yayık Ayran 135 TL. Eklemek istediğiniz bir şey var mı?",
  "Yok, hepsi bu kadar.",
  "Hemen servis ediyorum efendim."),

r("Dört limonata.",
  "Memnuniyetle, 4 Limonata 280 TL. Başka bir arzunuz var mı?",
  "Teşekkürler, şimdilik bu kadar.",
  "Birazdan masanıza getiriyorum efendim."),

r("İki şalgam suyu olsun.",
  "Tabii, 2 Şalgam Suyu 100 TL. İlaveten bir arzunuz olur mu?",
  "Hayır, hepsi bu.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("Bir mercimek, bir mantar çorbası.",
  "Elbette, Mercimek Çorbası 85 TL ve Kremalı Mantar Çorbası 95 TL. Başka isteğiniz var mı?",
  "Yeter bu kadar.",
  "Siparişinizi hemen hazırlatıyorum efendim."),

r("Köfte ve salata alayım.",
  "Memnuniyetle, Izgara Köfte 240 TL ve Izgara Tavuk Salata 210 TL. Başka bir arzunuz var mı?",
  "Yok, teşekkürler.",
  "Hemen hazırlıyorum, kısa sürede masanızda olacak."),

r("Döner ve ayran.",
  "Tabii, Et Döner 280 TL ve Yayık Ayran 45 TL. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu.",
  "Birazdan servis ediyorum efendim."),

r("Sütlaç ve limonata verir misiniz?",
  "Elbette, Fırın Sütlaç 100 TL ve Limonata 70 TL. Ekleyeceğimiz bir şey var mı?",
  "Teşekkürler, şimdilik yeterli.",
  "Hemen getiriyorum efendim, iyi günler."),

r("Künefe ile şalgam suyu rica ediyorum.",
  "Memnuniyetle, Künefe 140 TL ve Şalgam Suyu 50 TL. Başka bir arzunuz var mı?",
  "Hayır, bu kadar.",
  "Kısa sürede masanıza servis ediyorum."),

r("Mercimek çorbası ve ayran alalım.",
  "Tabii, Mercimek Çorbası 85 TL ve Yayık Ayran 45 TL. Eklemek istediğiniz bir şey var mı?",
  "Yeterli, teşekkürler.",
  "Siparişinizi hemen hazırlıyorum efendim."),

r("Köfte ve döner.",
  "Elbette, Izgara Köfte 240 TL ve Et Döner 280 TL. Başka bir isteğiniz var mı?",
  "Yok hepsi bu.",
  "Birazdan masanıza getiriyorum efendim."),

r("Salata ile limonata.",
  "Memnuniyetle, Izgara Tavuk Salata 210 TL ve Limonata 70 TL. İlaveten bir arzunuz olur mu?",
  "Hayır teşekkürler.",
  "Hemen hazırlatıyorum, afiyet olsun."),

r("Sütlaç ve ayran olsun.",
  "Tabii, Fırın Sütlaç 100 TL ve Yayık Ayran 45 TL. Başka bir arzunuz var mı?",
  "Hepsi bu kadar.",
  "Birazdan servis ediyorum efendim."),

r("Mantar çorbası ve şalgam suyu.",
  "Elbette, Kremalı Mantar Çorbası 95 TL ve Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Yeter, teşekkürler.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("İki mercimek ve iki köfte.",
  "Memnuniyetle, 2 Mercimek Çorbası 170 TL ve 2 Izgara Köfte 480 TL. Başka arzunuz var mı?",
  "Hayır, hepsi bu.",
  "Hemen hazırlıyorum efendim, afiyet olsun."),

r("Bir döner bir künefe.",
  "Tabii, Et Döner 280 TL ve Künefe 140 TL. Ekleyeceğimiz bir şey var mı?",
  "Yok, şimdilik bu kadar.",
  "Birazdan servis ediyorum efendim."),

r("İki salata bir limonata.",
  "Elbette, 2 Izgara Tavuk Salata 420 TL ve Limonata 70 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler, yeterli.",
  "Siparişinizi hemen hazırlatıyorum."),

r("Üç ayran iki sütlaç alayım.",
  "Memnuniyetle, 3 Yayık Ayran 135 TL ve 2 Fırın Sütlaç 200 TL. Başka arzunuz var mı?",
  "Hayır hepsi bu.",
  "Hemen masanıza getiriyorum efendim."),

r("Köfte, salata ve ayran.",
  "Tabii, Izgara Köfte 240 TL, Izgara Tavuk Salata 210 TL ve Yayık Ayran 45 TL. Başka isteğiniz var mı?",
  "Yeter bu kadar.",
  "Birazdan masanıza servis ediyorum, afiyet olsun."),

r("Döner, künefe ve limonata rica ediyorum.",
  "Elbette, Et Döner 280 TL, Künefe 140 TL ve Limonata 70 TL. Eklemek istediğiniz bir şey var mı?",
  "Yok, hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("Mercimek, köfte ve sütlaç.",
  "Memnuniyetle, Mercimek Çorbası 85 TL, Izgara Köfte 240 TL ve Fırın Sütlaç 100 TL. Başka bir arzunuz var mı?",
  "Teşekkürler, yeterli.",
  "Siparişinizi hızlıca iletiyorum, iyi günler."),

r("Mantar çorbası ve döner verir misiniz?",
  "Tabii, Kremalı Mantar Çorbası 95 TL ve Et Döner 280 TL. Başka bir isteğiniz var mı?",
  "Hayır, şimdilik bu kadar.",
  "Birazdan masanıza getiriyorum efendim."),

r("Bir salata iki ayran.",
  "Elbette, Izgara Tavuk Salata 210 TL ve 2 Yayık Ayran 90 TL. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("İki künefe bir limonata.",
  "Memnuniyetle, 2 Künefe 280 TL ve Limonata 70 TL. Başka bir arzunuz var mı?",
  "Hepsi bu kadar.",
  "Kısa sürede servis ediyorum efendim."),

r("Köfte ile sütlaç.",
  "Tabii, Izgara Köfte 240 TL ve Fırın Sütlaç 100 TL. Ekleyeceğimiz bir şey var mı?",
  "Teşekkürler, yeter.",
  "Hemen masanıza yönlendiriyorum."),

r("Döner ve şalgam suyu alalım.",
  "Elbette, Et Döner 280 TL ve Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Hayır, hepsi bu.",
  "Birazdan getiriyorum efendim, afiyet olsun."),

r("Mantar çorbası ile salata olsun.",
  "Memnuniyetle, Kremalı Mantar Çorbası 95 TL ve Izgara Tavuk Salata 210 TL. Başka arzunuz var mı?",
  "Yok şimdilik başka bir şey istemiyorum.",
  "Hemen hazırlatıyorum efendim."),

r("Mercimek çorbası, ayran.",
  "Tabii, Mercimek Çorbası 85 TL ve Yayık Ayran 45 TL. Başka bir arzunuz var mı?",
  "Teşekkür ederim, hepsi bu.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("İki döner iki limonata.",
  "Elbette, 2 Et Döner 560 TL ve 2 Limonata 140 TL. Eklemek istediğiniz bir şey var mı?",
  "Yeterli bu kadar.",
  "Kısa sürede masanıza getiriyorum efendim."),

r("Üç köfte üç ayran verir misiniz?",
  "Memnuniyetle, 3 Izgara Köfte 720 TL ve 3 Yayık Ayran 135 TL. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("Sütlaç ve şalgam suyu rica ediyorum.",
  "Tabii, Fırın Sütlaç 100 TL ve Şalgam Suyu 50 TL. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Birazdan servis ediyorum efendim."),

# 48-50 (generated)
r("Bir mercimek çorbası, bir limonata.",
  "Memnuniyetle, Mercimek Çorbası 85 TL ve Limonata 70 TL. Başka bir arzunuz var mı?",
  "Hayır yeterli.",
  "Hemen hazırlıyorum efendim."),

r("Bir fırın sütlaç ve bir şalgam suyu.",
  "Tabii, Fırın Sütlaç 100 TL ve Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler, bu kadar.",
  "Birazdan servis ediyorum efendim."),

r("Kremalı mantar çorbası ve ayran alalım.",
  "Elbette, Kremalı Mantar Çorbası 95 TL ve Yayık Ayran 45 TL. Ekleyeceğimiz bir şey var mı?",
  "Yok hepsi bu.",
  "Siparişinizi hemen iletiyorum efendim."),

# ========== GRUP B – 3 tur: önce menü sorusu, sonra sipariş (46) ==========

r("Künefe ile çayınız var mı?",
  "Çayımız yok, içecek olarak Limonata, Ayran veya Şalgam Suyu tercih edebilirsiniz. Ne istersiniz?",
  "O zaman bir limonata ve künefe alayım.",
  "Memnuniyetle, Künefe 140 TL ve Limonata 70 TL. Başka bir arzunuz var mı?",
  "Hepsi bu kadar.",
  "Hemen hazırlatıyorum efendim, afiyet olsun."),

r("Tatlı olarak neleriniz var?",
  "Tatlı olarak Fırın Sütlaç ve Künefe seçeneklerimiz bulunuyor. Ne arzu edersiniz?",
  "Bir sütlaç alayım.",
  "Tabii, Fırın Sütlaç 100 TL. Başka bir isteğiniz var mı?",
  "Başka bir şey istemiyorum, teşekkürler.",
  "Siparişinizi hemen masanıza getiriyorum, iyi günler dileriz."),

r("Çorbalarınız neler?",
  "Mercimek Çorbası ve Kremalı Mantar Çorbası sunuyoruz. Hangisini arzu edersiniz?",
  "Bir mercimek alayım.",
  "Elbette, Mercimek Çorbası 85 TL. Ekleyeceğimiz bir şey var mı?",
  "Hayır, hepsi bu.",
  "Birazdan masanıza servis ediyorum efendim."),

r("Ana yemek ne tavsiye edersiniz?",
  "Izgara Köfte ve Et Döner en çok tercih edilen yemeklerimiz. Hangisini istersiniz?",
  "Bir et döner alalım.",
  "Memnuniyetle, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Teşekkürler, yeterli.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("Soğuk içecekleriniz nelerdir?",
  "Yayık Ayran, Limonata ve Şalgam Suyu seçeneklerimiz mevcut. Ne içerdiniz?",
  "İki ayran rica ediyorum.",
  "Tabii, 2 Yayık Ayran 90 TL. İlaveten bir arzunuz olur mu?",
  "Yok, hepsi bu kadar.",
  "Siparişinizi hemen iletiyorum efendim."),

r("Menüde hangi tatlılar var?",
  "Fırın Sütlaç ve Künefe tatlılarımız bulunuyor. Hangisini arzu edersiniz?",
  "İki künefe verir misiniz?",
  "Elbette, 2 Künefe 280 TL. Başka bir isteğiniz var mı?",
  "Teşekkür ederim, yeter.",
  "Kısa sürede masanıza getiriyorum."),

r("Et yemekleriniz neler?",
  "Et yemeği olarak Izgara Köfte ve Et Döner sunuyoruz. Ne arzu edersiniz?",
  "Bir porsiyon köfte olsun.",
  "Memnuniyetle, Izgara Köfte 240 TL. Eklemek istediğiniz bir şey var mı?",
  "Şimdilik başka bir şey istemiyorum.",
  "Hemen hazırlıyorum efendim, afiyet olsun."),

r("Çorba var mı?",
  "Evet, Mercimek ve Kremalı Mantar Çorbası mevcut. Hangisini istersiniz?",
  "Mantar çorbası alayım.",
  "Tabii, Kremalı Mantar Çorbası 95 TL. Başka bir arzunuz var mı?",
  "Hayır, hepsi bu.",
  "Birazdan servis ediyorum efendim."),

r("Hafif bir şeyler ne var?",
  "Hafif bir öğün için Izgara Tavuk Salata tercih edebilirsiniz. Arzu eder misiniz?",
  "Tamam, bir tavuk salata olsun.",
  "Elbette, Izgara Tavuk Salata 210 TL. Başka bir isteğiniz var mı?",
  "Yok teşekkürler.",
  "Siparişinizi hızla hazırlıyorum efendim."),

r("Asitli içecek var mı?",
  "Asitli içeceğimiz bulunmuyor, Limonata, Ayran veya Şalgam Suyu alabilirsiniz. Hangisini istersiniz?",
  "Bir limonata alayım.",
  "Memnuniyetle, Limonata 70 TL. İlaveten bir arzunuz olur mu?",
  "Teşekkürler, yeterli.",
  "Hemen masanıza getiriyorum."),

r("Tatlılardan en hafifi hangisi?",
  "Fırın Sütlaç en hafif tatlımızdır. Siparişinize ekleyelim mi?",
  "Evet, bir fırın sütlaç olsun.",
  "Tabii, Fırın Sütlaç 100 TL. Ekleyeceğimiz bir şey var mı?",
  "Hayır hepsi bu.",
  "Kısa sürede servis ediyorum efendim, afiyet olsun."),

r("Sıcak bir şeyler var mı içecek?",
  "Sıcak içeceğimiz yok, başlangıç olarak Mercimek veya Mantar Çorbası alabilirsiniz. İster misiniz?",
  "İki mercimek çorbası verin o zaman.",
  "Elbette, 2 Mercimek Çorbası 170 TL. Başka bir arzunuz var mı?",
  "Yok hepsi bu kadar.",
  "Hemen hazırlatıyorum efendim."),

r("Et döner mi köfte mi daha çok satıyor?",
  "İkisi de çok sevilir ancak Et Döner biraz daha fazla tercih ediliyor. Ne alırdınız?",
  "O zaman iki et döner alalım.",
  "Memnuniyetle, 2 Et Döner 560 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler, yeterli.",
  "Birazdan masanıza servis ediyorum."),

r("Acılı şalgam var mı?",
  "Sadece standart Şalgam Suyu servis ediyoruz. Arzu eder misiniz?",
  "Tamam, iki tane şalgam ver.",
  "Tabii, 2 Şalgam Suyu 100 TL. İlaveten bir arzunuz olur mu?",
  "Hayır hepsi bu.",
  "Hemen getiriyorum efendim, iyi günler."),

r("Künefe kaç dakika sürer?",
  "Künefemiz sıcak servis için hemen fırına verilir, kısa sürede hazırlanır. İster misiniz?",
  "Tamam bir künefe olsun.",
  "Elbette, Künefe 140 TL. Eklemek istediğiniz bir şey var mı?",
  "Yok teşekkürler.",
  "Kısa sürede masanıza yönlendiriyorum."),

r("Salata çeşitleriniz neler?",
  "Sadece Izgara Tavuk Salata seçeneğimiz bulunuyor. Sipariş etmek ister misiniz?",
  "Evet, bir salata alayım.",
  "Memnuniyetle, Izgara Tavuk Salata 210 TL. Başka bir arzunuz var mı?",
  "Şimdilik bu kadar.",
  "Hemen hazırlıyorum efendim."),

r("Sütlü tatlı var mı?",
  "Evet, Fırın Sütlaç sunuyoruz. Arzu eder misiniz?",
  "İki sütlaç rica ediyorum.",
  "Tabii, 2 Fırın Sütlaç 200 TL. Başka bir isteğiniz var mı?",
  "Hayır, hepsi bu kadar.",
  "Hemen masanıza servis ediyorum."),

r("Meyve suyu var mı?",
  "Meyve suyumuz yok, Limonata, Şalgam Suyu veya Ayran alabilirsiniz. Hangisini istersiniz?",
  "İki limonata verir misiniz?",
  "Elbette, 2 Limonata 140 TL. Ekleyeceğimiz bir şey var mı?",
  "Teşekkür ederim, yeter.",
  "Birazdan getiriyorum efendim."),

r("En hızlı çıkacak yemek nedir?",
  "Çorbalarımız anında servis edilir, Mercimek veya Mantar Çorbası ister misiniz?",
  "Bir mercimek, bir mantar olsun.",
  "Memnuniyetle, Mercimek Çorbası 85 TL ve Kremalı Mantar Çorbası 95 TL. Başka arzunuz var mı?",
  "Yok hepsi bu.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("Izgara olarak neleriniz var?",
  "Izgara Köfte ve Izgara Tavuk Salata sunuyoruz. Ne arzu edersiniz?",
  "İki ızgara köfte alalım.",
  "Tabii, 2 Izgara Köfte 480 TL. Başka bir isteğiniz var mı?",
  "Yeterli, teşekkürler.",
  "Hemen hazırlıyorum efendim."),

r("Tatlı şerbetli mi olsun sütlü mü kararsız kaldım.",
  "Hafif isterseniz Fırın Sütlaç, şerbetli isterseniz Künefe alabilirsiniz. Hangisi olsun?",
  "Künefe alalım iki tane.",
  "Elbette, 2 Künefe 280 TL. İlaveten bir arzunuz olur mu?",
  "Hayır hepsi bu.",
  "Sıcak sıcak masanıza getiriyorum."),

r("Vegan bir seçeneğiniz var mı?",
  "Bu konuda bilgim yok, personelimize sorabilirsiniz.",
  "O zaman sadece bir limonata alayım.",
  "Memnuniyetle, Limonata 70 TL. Eklemek istediğiniz bir şey var mı?",
  "Hayır teşekkürler.",
  "Hemen servis ediyorum efendim."),

r("Ev yapımı içeceğiniz var mı?",
  "Limonata ve Yayık Ayran tercih edebilirsiniz. Hangisini istersiniz?",
  "Bir ayran olsun.",
  "Tabii, Yayık Ayran 45 TL. Başka bir arzunuz var mı?",
  "Yok, hepsi bu kadar.",
  "Birazdan getiriyorum efendim, afiyet olsun."),

r("Şalgam acı mı?",
  "Standart lezzette bir Şalgam Suyu servis ediyoruz. Arzu eder misiniz?",
  "Tamam bir şalgam alayım.",
  "Elbette, Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler, yeter.",
  "Siparişinizi hemen hazırlatıyorum."),

r("Tavuk yemeği var mı?",
  "Evet, Izgara Tavuk Salata bulunuyor. Siparişinize ekleyelim mi?",
  "Evet, iki tane salata alalım.",
  "Memnuniyetle, 2 Izgara Tavuk Salata 420 TL. Ekleyeceğimiz bir şey var mı?",
  "Hayır hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("Çorbalarınız çok sıcak mı servis ediliyor?",
  "Evet, çorbalarımız sıcak servis edilmektedir. Mercimek veya Mantar Çorbası ister misiniz?",
  "Bir mantar çorbası verin.",
  "Tabii, Kremalı Mantar Çorbası 95 TL. İlaveten bir arzunuz olur mu?",
  "Yok şimdilik başka bir şey istemiyorum.",
  "Birazdan masanıza getiriyorum."),

r("Döner porsiyonu doyurucu mu?",
  "Evet, Et Döner oldukça doyurucu bir porsiyondur. Arzu eder misiniz?",
  "Tamam bir döner alayım.",
  "Elbette, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Teşekkür ederim, hepsi bu.",
  "Hemen hazırlatıyorum efendim, afiyet olsun."),

r("Açık ayranınız var mı?",
  "Açık olarak lezzetli Yayık Ayran servis ediyoruz. Kaç tane istersiniz?",
  "Üç tane ayran alalım.",
  "Memnuniyetle, 3 Yayık Ayran 135 TL. Başka bir isteğiniz var mı?",
  "Yeterli bu kadar.",
  "Hemen getiriyorum efendim."),

r("Tatlılardan hangisi daha çok satılıyor?",
  "Künefe ve Fırın Sütlaç eşit derecede seviliyor. Hangisini tercih edersiniz?",
  "Bir sütlaç alayım.",
  "Tabii, Fırın Sütlaç 100 TL. Eklemek istediğiniz bir şey var mı?",
  "Hayır hepsi bu.",
  "Kısa sürede servis ediyorum efendim."),

r("Köfte acılı mıdır?",
  "Izgara Köfte acısız ve çok lezzetlidir. Arzu eder misiniz?",
  "İki porsiyon köfte olsun.",
  "Elbette, 2 Izgara Köfte 480 TL. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("Künefe üstüne dondurma var mı?",
  "Bu konuda bilgim yok, personelimize sorabilirsiniz. Sadece Künefe ister misiniz?",
  "Tamam sadece künefe ver.",
  "Memnuniyetle, Künefe 140 TL. İlaveten bir arzunuz olur mu?",
  "Hayır hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("İçecek ne verebilirsin?",
  "Yayık Ayran, Limonata ve Şalgam Suyu içeceklerimizdendir. Ne istersiniz?",
  "Bir limonata, bir ayran.",
  "Tabii, Limonata 70 TL ve Yayık Ayran 45 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler, yeterli.",
  "Birazdan getiriyorum efendim."),

r("Ana menüde ne yiyebiliriz?",
  "Izgara Köfte, Et Döner ve Izgara Tavuk Salata yiyebilirsiniz. Hangisi olsun?",
  "Döner ve köfte alalım.",
  "Elbette, Et Döner 280 TL ve Izgara Köfte 240 TL. Başka arzunuz var mı?",
  "Yok hepsi bu kadar.",
  "Hemen hazırlatıyorum, iyi günler."),

r("Önden içecek çorba ne var?",
  "Mercimek ve Kremalı Mantar Çorbası ile çeşitli içeceklerimiz mevcut. Ne arzu ederdiniz?",
  "Bir mercimek, bir şalgam.",
  "Memnuniyetle, Mercimek Çorbası 85 TL ve Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler, şimdilik bu kadar.",
  "Kısa sürede servis ediyorum efendim."),

r("Bana menüde ne tatlı var sayar mısın?",
  "Tatlı olarak Fırın Sütlaç ve Künefe sunuyoruz. Hangisini istersiniz?",
  "Bir fırın sütlaç olsun.",
  "Tabii, Fırın Sütlaç 100 TL. Ekleyeceğimiz bir şey var mı?",
  "Hayır hepsi bu.",
  "Birazdan masanıza getiriyorum."),

r("Mantar çorbası var mı şu an?",
  "Evet, Kremalı Mantar Çorbası sıcak servis için hazır. Arzu eder misiniz?",
  "İki tane alalım.",
  "Elbette, 2 Kremalı Mantar Çorbası 190 TL. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Siparişinizi hemen hazırlatıyorum."),

r("Hangi dönerden yapıyorsunuz?",
  "Sadece lezzetli Et Döner sunuyoruz. Siparişinize ekleyelim mi?",
  "Tamam bir döner ver.",
  "Memnuniyetle, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Yeterli bu kadar.",
  "Hemen hazırlıyorum efendim, afiyet olsun."),

r("Diyete uygun salata ne var?",
  "Izgara Tavuk Salata tercih edebilirsiniz. Arzu eder misiniz?",
  "Evet, bir tavuk salata alayım.",
  "Tabii, Izgara Tavuk Salata 210 TL. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu.",
  "Birazdan servis ediyorum efendim."),

r("Çocuklar için hangi çorba iyi olur?",
  "Mercimek Çorbası çocuklar tarafından çok sevilir. Kaç tane istersiniz?",
  "İki mercimek alalım.",
  "Elbette, 2 Mercimek Çorbası 170 TL. Eklemek istediğiniz bir şey var mı?",
  "Teşekkürler, yeter.",
  "Hemen hazırlatıyorum, iyi günler."),

r("Ayranınız nasıl?",
  "Çok lezzetli ve taze Yayık Ayran servis ediyoruz. Arzu eder misiniz?",
  "Üç ayran verin.",
  "Memnuniyetle, 3 Yayık Ayran 135 TL. Başka bir arzunuz var mı?",
  "Yok hepsi bu.",
  "Hemen masanıza getiriyorum efendim."),

r("Tatlı olarak fırında pişen ne var?",
  "Tatlı olarak Fırın Sütlaç servisimiz var. İster misiniz?",
  "İki fırın sütlaç alayım.",
  "Tabii, 2 Fırın Sütlaç 200 TL. Başka bir isteğiniz var mı?",
  "Hayır, teşekkürler.",
  "Sıcak ve taze olarak hemen getiriyorum."),

r("Limonata taze mi?",
  "Evet, Limonata çok taze ve serinleticidir. Arzu eder misiniz?",
  "Dört limonata olsun.",
  "Elbette, 4 Limonata 280 TL. İlaveten bir arzunuz olur mu?",
  "Yeter bu kadar.",
  "Kısa sürede servis ediyorum efendim."),

r("Köfte kaç gram?",
  "Bu konuda bilgim yok, personelimize sorabilirsiniz. Izgara Köfte ister misiniz?",
  "Tamam bir köfte alayım.",
  "Memnuniyetle, Izgara Köfte 240 TL. Başka bir arzunuz var mı?",
  "Yok hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("Dönerin yanına hangi içeceği önerirsiniz?",
  "Et Döner yanına Yayık Ayran çok yakışır. İkisinden de ister misiniz?",
  "Olur, bir döner bir ayran.",
  "Tabii, Et Döner 280 TL ve Yayık Ayran 45 TL. Ekleyeceğimiz bir şey var mı?",
  "Hayır teşekkürler.",
  "Birazdan masanıza getiriyorum."),

r("Salatanın içinde ne var?",
  "Bu konuda bilgim yok, personelimize sorabilirsiniz. Izgara Tavuk Salata alırdınız mı?",
  "Evet bir salata olsun.",
  "Elbette, Izgara Tavuk Salata 210 TL. Başka bir isteğiniz var mı?",
  "Teşekkürler hepsi bu.",
  "Siparişinizi hemen hazırlatıyorum."),

r("En sevilen çorbanız hangisi?",
  "Mercimek ve Kremalı Mantar Çorbası da çok sevilir. Hangisi olsun?",
  "Mantar çorbası alayım.",
  "Memnuniyetle, Kremalı Mantar Çorbası 95 TL. Başka bir arzunuz var mı?",
  "Şimdilik yeterli.",
  "Hemen mutfağa iletiyorum efendim."),

# ========== GRUP C – 3 tur: sipariş + ek sipariş + kapanış (50) ==========

r("Et döner verir misiniz?",
  "Elbette, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Yanına bir de ayran ekleyelim.",
  "Memnuniyetle, Yayık Ayran 45 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu.",
  "Siparişlerinizi hemen hazırlatıyorum efendim, afiyet olsun."),

r("Bir porsiyon ızgara köfte istiyorum.",
  "Tabii, Izgara Köfte 240 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir porsiyon da fırın sütlaç verin.",
  "Elbette, Fırın Sütlaç 100 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Birazdan servis ediyorum efendim."),

r("Bana mercimek çorbası alayım.",
  "Memnuniyetle, Mercimek Çorbası 85 TL. İlaveten bir arzunuz olur mu?",
  "Üstüne et döner ekleyelim.",
  "Tabii, Et Döner 280 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Hepsi bu kadar.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("İki tane limonata rica ediyorum.",
  "Elbette, 2 Limonata 140 TL. Başka bir arzunuz var mı?",
  "Bir de tavuk salata olsun.",
  "Memnuniyetle, Izgara Tavuk Salata 210 TL olarak eklendi. Eklemek istediğiniz bir şey var mı?",
  "Hayır yeterli.",
  "Kısa sürede masanıza getiriyorum."),

r("Kremalı mantar çorbası alalım.",
  "Tabii, Kremalı Mantar Çorbası 95 TL. Başka bir isteğiniz var mı?",
  "Yanına ızgara köfte de ekle.",
  "Elbette, Izgara Köfte 240 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Teşekkürler hepsi bu.",
  "Hemen hazırlatıyorum efendim."),

r("Künefe istiyorum.",
  "Memnuniyetle, Künefe 140 TL. İlaveten bir arzunuz olur mu?",
  "Yanına şalgam suyu da alayım.",
  "Tabii, Şalgam Suyu 50 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Yok teşekkürler.",
  "Sıcak sıcak hemen getiriyorum."),

r("İki tane ayran.",
  "Elbette, 2 Yayık Ayran 90 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir fırın sütlaç daha ekler misin?",
  "Memnuniyetle, Fırın Sütlaç 100 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hepsi bu.",
  "Birazdan masanıza servis ediyorum."),

r("Izgara tavuk salata verir misin?",
  "Tabii, Izgara Tavuk Salata 210 TL. Başka bir arzunuz var mı?",
  "Bir de limonata ekleyelim.",
  "Elbette, Limonata 70 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Yeter bu kadar.",
  "Siparişinizi hemen hazırlıyorum efendim."),

r("Üç et döner.",
  "Memnuniyetle, 3 Et Döner 840 TL. İlaveten bir arzunuz olur mu?",
  "Üç de ayran ekle.",
  "Tabii, 3 Yayık Ayran 135 TL olarak eklendi. Eklemek istediğiniz bir şey var mı?",
  "Hayır hepsi bu.",
  "Hemen hazırlatıyorum, afiyet olsun."),

r("Mercimek çorbası.",
  "Elbette, Mercimek Çorbası 85 TL. Başka bir isteğiniz var mı?",
  "Bir tane daha mercimek ekleyelim.",
  "Memnuniyetle, 1 Mercimek Çorbası 85 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Kısa sürede masanıza getiriyorum."),

r("Bir köfte alayım.",
  "Tabii, Izgara Köfte 240 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir tane şalgam suyu olsun.",
  "Elbette, Şalgam Suyu 50 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Şimdilik bu kadar.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("İki mantar çorbası.",
  "Memnuniyetle, 2 Kremalı Mantar Çorbası 190 TL. Başka bir arzunuz var mı?",
  "Bir de tavuk salata ver.",
  "Tabii, Izgara Tavuk Salata 210 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Hayır hepsi bu.",
  "Birazdan servis ediyorum efendim."),

r("Künefe alalım.",
  "Elbette, Künefe 140 TL. Başka bir isteğiniz var mı?",
  "Yanına iki limonata ekleyelim.",
  "Memnuniyetle, 2 Limonata 140 TL siparişinize eklendi. Eklemek istediğiniz bir şey var mı?",
  "Teşekkürler, yeterli.",
  "Hemen hazırlıyorum, iyi günler."),

r("Fırın sütlaç verir misin?",
  "Tabii, Fırın Sütlaç 100 TL. Başka bir arzunuz var mı?",
  "Bir porsiyon et döner de olsun.",
  "Elbette, Et Döner 280 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Yok hepsi bu.",
  "Kısa sürede masanıza yönlendiriyorum."),

r("İki tane ayran.",
  "Memnuniyetle, 2 Yayık Ayran 90 TL. İlaveten bir arzunuz olur mu?",
  "Bir de ızgara köfte ekleyelim.",
  "Tabii, Izgara Köfte 240 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Yeter bu kadar.",
  "Siparişinizi hemen hazırlatıyorum efendim."),

r("Şalgam suyu rica ediyorum.",
  "Elbette, Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Yanına mercimek çorbası alayım.",
  "Memnuniyetle, Mercimek Çorbası 85 TL olarak eklendi. Ekleyeceğimiz bir şey var mı?",
  "Hayır hepsi bu kadar.",
  "Birazdan getiriyorum efendim, afiyet olsun."),

r("İki döner.",
  "Tabii, 2 Et Döner 560 TL. Başka bir arzunuz var mı?",
  "Bir mantar çorbası da ekleyelim.",
  "Elbette, Kremalı Mantar Çorbası 95 TL siparişinize eklendi. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Hemen hazırlıyorum efendim."),

r("Tavuk salata.",
  "Memnuniyetle, Izgara Tavuk Salata 210 TL. Başka bir isteğiniz var mı?",
  "Üstüne fırın sütlaç olsun.",
  "Tabii, Fırın Sütlaç 100 TL olarak eklendi. Eklemek istediğiniz bir şey var mı?",
  "Hepsi bu.",
  "Kısa sürede servis ediyorum."),

r("Limonata verin.",
  "Elbette, Limonata 70 TL. Başka bir arzunuz var mı?",
  "Bir de künefe ekler misiniz?",
  "Memnuniyetle, Künefe 140 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Teşekkürler yeterli.",
  "Sıcak sıcak hemen masanıza getiriyorum."),

r("İki tane köfte.",
  "Tabii, 2 Izgara Köfte 480 TL. İlaveten bir arzunuz olur mu?",
  "Yanına iki ayran da ekleyelim.",
  "Elbette, 2 Yayık Ayran 90 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hayır, bu kadar.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("Üç mercimek çorbası.",
  "Memnuniyetle, 3 Mercimek Çorbası 255 TL. Başka bir isteğiniz var mı?",
  "Üç tane de sütlaç olsun.",
  "Tabii, 3 Fırın Sütlaç 300 TL siparişinize eklendi. Ekleyeceğimiz bir şey var mı?",
  "Yok hepsi bu.",
  "Hemen hazırlatıyorum efendim, afiyet olsun."),

r("Bir et döner.",
  "Elbette, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Bir döner daha ekleyelim.",
  "Memnuniyetle, 1 Et Döner 280 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yeterli bu kadar.",
  "Birazdan masanıza getiriyorum."),

r("Şalgam suyu alalım.",
  "Tabii, Şalgam Suyu 50 TL. Başka bir isteğiniz var mı?",
  "Bir de ızgara tavuk salata ver.",
  "Elbette, Izgara Tavuk Salata 210 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Hayır hepsi bu.",
  "Siparişinizi hemen hazırlıyorum efendim."),

r("Künefe rica ediyorum.",
  "Memnuniyetle, Künefe 140 TL. Eklemek istediğiniz bir şey var mı?",
  "Yanına limonata da olsun.",
  "Tabii, Limonata 70 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Teşekkürler, yeter.",
  "Kısa sürede masanıza yönlendiriyorum."),

r("Bir ayran.",
  "Elbette, Yayık Ayran 45 TL. Başka bir isteğiniz var mı?",
  "Bir de mercimek çorbası ekleyelim.",
  "Memnuniyetle, Mercimek Çorbası 85 TL siparişinize eklendi. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Hemen hazırlatıyorum efendim, iyi günler."),

r("Mantar çorbası.",
  "Tabii, Kremalı Mantar Çorbası 95 TL. Başka bir arzunuz var mı?",
  "Yanına döner ekler misin?",
  "Elbette, Et Döner 280 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu kadar.",
  "Birazdan servis ediyorum efendim."),

r("Salata istiyorum.",
  "Memnuniyetle, Izgara Tavuk Salata 210 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir fırın sütlaç da ver.",
  "Tabii, Fırın Sütlaç 100 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Şimdilik bu kadar.",
  "Siparişinizi hemen iletiyorum."),

r("İki tane şalgam suyu.",
  "Elbette, 2 Şalgam Suyu 100 TL. Başka bir isteğiniz var mı?",
  "İki de köfte olsun.",
  "Memnuniyetle, 2 Izgara Köfte 480 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yok hepsi bu.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("Sütlaç alayım.",
  "Tabii, Fırın Sütlaç 100 TL. Başka bir arzunuz var mı?",
  "Limonata da ekleyelim yanına.",
  "Elbette, Limonata 70 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Yeterli, teşekkürler.",
  "Kısa sürede masanıza getiriyorum."),

r("Bir döner.",
  "Memnuniyetle, Et Döner 280 TL. Eklemek istediğiniz bir şey var mı?",
  "Künefe de verin üstüne.",
  "Tabii, Künefe 140 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hayır hepsi bu.",
  "Sıcak sıcak hemen servis ediyorum."),

# 20 generated Grup C records
r("İki köfte.",
  "Tabii, 2 Izgara Köfte 480 TL. Başka bir arzunuz var mı?",
  "Bir fırın sütlaç da ekleyelim.",
  "Elbette, Fırın Sütlaç 100 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Yok teşekkürler.",
  "Hemen hazırlıyorum efendim."),

r("Bir mercimek çorbası, bir ayran.",
  "Memnuniyetle, Mercimek Çorbası 85 TL ve Yayık Ayran 45 TL. Başka bir arzunuz var mı?",
  "Künefe de alalım yanına.",
  "Tabii, Künefe 140 TL siparişinize eklendi. Ekleyeceğimiz bir şey var mı?",
  "Hayır hepsi bu.",
  "Birazdan getiriyorum efendim, afiyet olsun."),

r("Üç limonata.",
  "Elbette, 3 Limonata 210 TL. Başka bir isteğiniz var mı?",
  "Bir ızgara köfte de ekleyelim.",
  "Memnuniyetle, Izgara Köfte 240 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yeterli bu kadar.",
  "Kısa sürede servis ediyorum efendim."),

r("Bir şalgam suyu.",
  "Tabii, Şalgam Suyu 50 TL. İlaveten bir arzunuz olur mu?",
  "Bir de et döner ekleyelim.",
  "Elbette, Et Döner 280 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Tamam hepsi bu.",
  "Hemen hazırlatıyorum efendim."),

r("İki ayran.",
  "Memnuniyetle, 2 Yayık Ayran 90 TL. Eklemek istediğiniz bir şey var mı?",
  "Bir mantar çorbası da alayım.",
  "Tabii, Kremalı Mantar Çorbası 95 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yok hepsi bu kadar.",
  "Birazdan servis ediyorum efendim."),

r("Izgara tavuk salata.",
  "Elbette, Izgara Tavuk Salata 210 TL. Başka bir arzunuz var mı?",
  "Bir şalgam suyu da ekle.",
  "Memnuniyetle, Şalgam Suyu 50 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Teşekkürler yeterli.",
  "Siparişinizi hemen iletiyorum."),

r("İki fırın sütlaç.",
  "Tabii, 2 Fırın Sütlaç 200 TL. İlaveten bir arzunuz olur mu?",
  "Limonata da olsun bir tane.",
  "Elbette, Limonata 70 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hayır bu kadar.",
  "Kısa sürede masanıza getiriyorum."),

r("Bir mantar çorbası.",
  "Memnuniyetle, Kremalı Mantar Çorbası 95 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir döner de ver yanına.",
  "Tabii, Et Döner 280 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Yok teşekkürler.",
  "Hemen hazırlıyorum efendim, afiyet olsun."),

r("Üç ayran.",
  "Elbette, 3 Yayık Ayran 135 TL. Başka bir arzunuz var mı?",
  "Üç mercimek çorbası da ekleyelim.",
  "Memnuniyetle, 3 Mercimek Çorbası 255 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Hepsi bu.",
  "Siparişinizi hemen mutfağa iletiyorum."),

r("İki künefe.",
  "Tabii, 2 Künefe 280 TL. İlaveten bir arzunuz olur mu?",
  "İki de şalgam suyu ekleyelim.",
  "Elbette, 2 Şalgam Suyu 100 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yeterli teşekkürler.",
  "Sıcak sıcak hemen masanıza getiriyorum."),

r("Bir limonata.",
  "Memnuniyetle, Limonata 70 TL. Eklemek istediğiniz bir şey var mı?",
  "Bir ızgara tavuk salata da ver.",
  "Tabii, Izgara Tavuk Salata 210 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Tamam yeter.",
  "Birazdan servis ediyorum efendim."),

r("Bir et döner.",
  "Elbette, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Bir fırın sütlaç ekleyelim yanına.",
  "Memnuniyetle, Fırın Sütlaç 100 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Hayır hepsi bu.",
  "Kısa sürede masanıza yönlendiriyorum."),

r("İki mercimek çorbası.",
  "Tabii, 2 Mercimek Çorbası 170 TL. Başka bir isteğiniz var mı?",
  "İki de döner ekleyelim.",
  "Elbette, 2 Et Döner 560 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Hemen hazırlatıyorum efendim."),

r("Bir künefe.",
  "Memnuniyetle, Künefe 140 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir ayran da alayım.",
  "Tabii, Yayık Ayran 45 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Hepsi bu kadar.",
  "Birazdan masanıza getiriyorum efendim."),

r("Üç köfte.",
  "Elbette, 3 Izgara Köfte 720 TL. İlaveten bir arzunuz olur mu?",
  "Bir limonata ekleyelim.",
  "Memnuniyetle, Limonata 70 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Yok hepsi bu.",
  "Siparişinizi hemen iletiyorum, afiyet olsun."),

r("Bir fırın sütlaç.",
  "Tabii, Fırın Sütlaç 100 TL. Başka bir arzunuz var mı?",
  "Bir şalgam suyu da ver yanına.",
  "Elbette, Şalgam Suyu 50 TL olarak eklendi. Eklemek istediğiniz bir şey var mı?",
  "Hayır yeterli.",
  "Kısa sürede servis ediyorum efendim."),

r("İki tavuk salata.",
  "Memnuniyetle, 2 Izgara Tavuk Salata 420 TL. Başka bir isteğiniz var mı?",
  "İki de ayran ekleyelim.",
  "Tabii, 2 Yayık Ayran 90 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Teşekkürler hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("Bir şalgam.",
  "Elbette, Şalgam Suyu 50 TL. İlaveten bir arzunuz olur mu?",
  "Bir künefe de olsun.",
  "Memnuniyetle, Künefe 140 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Yok tamam.",
  "Sıcak sıcak masanıza yönlendiriyorum."),

r("Bir mantar, bir mercimek çorbası.",
  "Tabii, Kremalı Mantar Çorbası 95 TL ve Mercimek Çorbası 85 TL. Başka bir arzunuz var mı?",
  "Bir de limonata ekle.",
  "Elbette, Limonata 70 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu.",
  "Birazdan getiriyorum efendim, afiyet olsun."),

r("İki döner.",
  "Memnuniyetle, 2 Et Döner 560 TL. Ekleyeceğimiz bir şey var mı?",
  "İki de limonata olsun.",
  "Tabii, 2 Limonata 140 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Teşekkürler yeterli.",
  "Siparişinizi hızla hazırlatıyorum."),

# ========== GRUP D – 4 tur: tam konuşma akışı (39) ==========

r("Merhaba, kolay gelsin.",
  "Merhabalar, restoranımıza hoş geldiniz. Ne arzu edersiniz?",
  "Bir porsiyon köfte alayım.",
  "Tabii, Izgara Köfte 240 TL. Başka bir arzunuz var mı?",
  "Bir de limonata rica ediyorum.",
  "Elbette, Limonata 70 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yeterli bu kadar.",
  "Hemen hazırlıyorum, afiyet olsun efendim."),

r("İyi günler, menüye bakıyorduk.",
  "İyi günler efendim, restoranımıza hoş geldiniz. Ne sipariş etmek istersiniz?",
  "Bir mercimek çorbası olsun.",
  "Memnuniyetle, Mercimek Çorbası 85 TL. Başka bir isteğiniz var mı?",
  "Yanına et döner de ekleyelim.",
  "Tabii, Et Döner 280 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Hayır, teşekkürler.",
  "Birazdan masanıza getiriyorum, iyi günler."),

r("Selamlar.",
  "Selamlar efendim, restoranımıza hoş geldiniz. Ne arzu ederdiniz?",
  "Kremalı mantar çorbası alalım.",
  "Elbette, Kremalı Mantar Çorbası 95 TL. Ekleyeceğimiz bir şey var mı?",
  "İki tane de ayran olsun.",
  "Memnuniyetle, 2 Yayık Ayran 90 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hepsi bu kadar.",
  "Siparişinizi hemen hazırlatıyorum efendim."),

r("Günaydın.",
  "Günaydın efendim, hoş geldiniz. Buyurun, ne arzu edersiniz?",
  "İki limonata alalım.",
  "Tabii, 2 Limonata 140 TL. Başka bir isteğiniz var mı?",
  "Bir künefe de ekleyelim.",
  "Elbette, Künefe 140 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Tamam hepsi bu.",
  "Sıcak sıcak hemen masanıza getiriyorum, afiyet olsun."),

r("Sipariş verebilir miyiz?",
  "Buyurun efendim, ne arzu edersiniz?",
  "Izgara tavuk salata.",
  "Memnuniyetle, Izgara Tavuk Salata 210 TL. Eklemek istediğiniz bir şey var mı?",
  "Bir şalgam suyu da olsun.",
  "Tabii, Şalgam Suyu 50 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Yok hepsi bu.",
  "Birazdan servis ediyorum efendim."),

r("İyi akşamlar.",
  "İyi akşamlar efendim, hoş geldiniz. Ne arzu edersiniz?",
  "Bir et döner.",
  "Elbette, Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Yanına bir mantar çorbası.",
  "Memnuniyetle, Kremalı Mantar Çorbası 95 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Teşekkürler, yeterli.",
  "Hemen hazırlıyorum, kısa sürede masanızda olacak."),

r("Kolay gelsin, sipariş alacak mısınız?",
  "Memnuniyetle, buyurun ne arzu edersiniz?",
  "İki fırın sütlaç.",
  "Tabii, 2 Fırın Sütlaç 200 TL. Başka bir isteğiniz var mı?",
  "İki de limonata ekleyelim.",
  "Elbette, 2 Limonata 140 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Kısa sürede masanıza getiriyorum efendim."),

r("Merhaba, müsait misiniz?",
  "Evet efendim, buyurun. Ne arzu edersiniz?",
  "Bir porsiyon döner.",
  "Memnuniyetle, Et Döner 280 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir de mercimek çorbası ver.",
  "Tabii, Mercimek Çorbası 85 TL siparişinize eklendi. Başka bir arzunuz var mı?",
  "Hepsi bu.",
  "Siparişinizi hemen mutfağa iletiyorum, afiyet olsun."),

r("Selam, hazır mısınız?",
  "Selamlar efendim, buyurun ne arzu ederdiniz?",
  "Üç ayran istiyoruz.",
  "Elbette, 3 Yayık Ayran 135 TL. Başka bir isteğiniz var mı?",
  "Üç de köfte alalım.",
  "Memnuniyetle, 3 Izgara Köfte 720 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yeterli, teşekkürler.",
  "Birazdan masanıza servis ediyorum efendim."),

r("İyi günler, siparişimizi verebilir miyiz?",
  "İyi günler, tabii buyurun. Ne arzu edersiniz?",
  "İki mercimek çorbası.",
  "Tabii, 2 Mercimek Çorbası 170 TL. Başka bir arzunuz var mı?",
  "İki şalgam suyu da.",
  "Elbette, 2 Şalgam Suyu 100 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Hayır hepsi bu.",
  "Hemen hazırlatıyorum efendim, iyi günler."),

r("Köfte kaç TL?",
  "Izgara Köfte 240 TL. Sipariş etmek ister misiniz?",
  "Evet, bir köfte.",
  "Memnuniyetle, Izgara Köfte 240 TL. Başka bir arzunuz var mı?",
  "Bir de limonata ekleyelim.",
  "Tabii, Limonata 70 TL siparişinize eklendi. Ekleyeceğimiz bir şey var mı?",
  "Yok teşekkürler.",
  "Birazdan getiriyorum efendim."),

r("Döner ne kadar?",
  "Et Döner 280 TL. Arzu eder misiniz?",
  "İki döner alalım.",
  "Elbette, 2 Et Döner 560 TL. Başka bir isteğiniz var mı?",
  "İki de ayran.",
  "Memnuniyetle, 2 Yayık Ayran 90 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hayır hepsi bu.",
  "Hemen hazırlıyorum, afiyet olsun."),

r("Mercimek çorbası kaç lira?",
  "Mercimek Çorbası 85 TL. Siparişinize ekleyelim mi?",
  "Evet, iki tane.",
  "Tabii, 2 Mercimek Çorbası 170 TL. Başka bir arzunuz var mı?",
  "Bir ızgara köfte de.",
  "Elbette, Izgara Köfte 240 TL siparişinize eklendi. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Kısa sürede masanıza getiriyorum."),

r("Künefe ne kadar?",
  "Künefe 140 TL. İster misiniz?",
  "İki tane künefe.",
  "Memnuniyetle, 2 Künefe 280 TL. Başka bir isteğiniz var mı?",
  "İki şalgam suyu da.",
  "Tabii, 2 Şalgam Suyu 100 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hepsi bu.",
  "Sıcak sıcak hemen masanıza servis ediyorum."),

r("Ayran fiyatı ne?",
  "Yayık Ayran 45 TL. Arzu eder misiniz?",
  "Üç ayran.",
  "Elbette, 3 Yayık Ayran 135 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir de mantar çorbası.",
  "Memnuniyetle, Kremalı Mantar Çorbası 95 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Teşekkür ederim, yeter.",
  "Birazdan servis ediyorum efendim."),

r("Sütlaç kaç TL acaba?",
  "Fırın Sütlaç 100 TL. Siparişinize ekleyelim mi?",
  "Evet bir tane.",
  "Tabii, Fırın Sütlaç 100 TL. Başka bir arzunuz var mı?",
  "Bir de şalgam suyu.",
  "Elbette, Şalgam Suyu 50 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Yok hepsi bu.",
  "Hemen hazırlıyorum efendim."),

r("Limonata ne kadar?",
  "Limonata 70 TL. Arzu eder misiniz?",
  "Dört limonata.",
  "Memnuniyetle, 4 Limonata 280 TL. İlaveten bir arzunuz olur mu?",
  "İki de sütlaç ekle.",
  "Tabii, 2 Fırın Sütlaç 200 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Teşekkürler yeterli.",
  "Kısa sürede masanıza getiriyorum."),

r("Menüde çorba var mıydı?",
  "Evet, Mercimek Çorbası ve Kremalı Mantar Çorbası sunuyoruz. Ne alırdınız?",
  "İki mantar çorbası.",
  "Elbette, 2 Kremalı Mantar Çorbası 190 TL. Başka bir isteğiniz var mı?",
  "Yanına iki de ayran.",
  "Memnuniyetle, 2 Yayık Ayran 90 TL olarak eklendi. Eklemek istediğiniz bir şey var mı?",
  "Yok hepsi bu kadar.",
  "Siparişinizi hemen iletiyorum efendim."),

r("Tatlılarınız neler?",
  "Fırın Sütlaç ve Künefe tatlılarımız bulunuyor. Hangisini istersiniz?",
  "İki künefe alalım.",
  "Tabii, 2 Künefe 280 TL. Başka bir arzunuz var mı?",
  "İki de limonata olsun.",
  "Elbette, 2 Limonata 140 TL siparişinize eklendi. Başka bir isteğiniz var mı?",
  "Yeterli, teşekkürler.",
  "Sıcak sıcak hemen servis ediyorum efendim."),

r("Izgara yemek var mı?",
  "Evet, Izgara Köfte ve Izgara Tavuk Salata sunuyoruz. Ne arzu edersiniz?",
  "Bir köfte, bir salata.",
  "Memnuniyetle, Izgara Köfte 240 TL ve Izgara Tavuk Salata 210 TL. Başka bir arzunuz var mı?",
  "Bir de şalgam suyu ekle.",
  "Tabii, Şalgam Suyu 50 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Hayır hepsi bu.",
  "Birazdan masanıza getiriyorum, afiyet olsun."),

r("İçecek ne var?",
  "Yayık Ayran, Limonata ve Şalgam Suyu içeceklerimizdendir. Ne istersiniz?",
  "İki limonata.",
  "Elbette, 2 Limonata 140 TL. Başka bir isteğiniz var mı?",
  "Bir de ızgara köfte ekleyelim.",
  "Memnuniyetle, Izgara Köfte 240 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Kısa sürede masanıza servis ediyorum."),

r("Merhaba.",
  "Merhabalar efendim, hoş geldiniz. Ne arzu edersiniz?",
  "Bir döner.",
  "Tabii, Et Döner 280 TL. Ekleyeceğimiz bir şey var mı?",
  "Bir de sütlaç.",
  "Elbette, Fırın Sütlaç 100 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hepsi bu.",
  "Hemen hazırlatıyorum efendim, afiyet olsun."),

r("İyi günler.",
  "İyi günler efendim, buyurun ne arzu ederdiniz?",
  "İki mercimek çorbası.",
  "Memnuniyetle, 2 Mercimek Çorbası 170 TL. İlaveten bir arzunuz olur mu?",
  "Bir mantar çorbası da.",
  "Tabii, Kremalı Mantar Çorbası 95 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Teşekkürler yeter.",
  "Birazdan masanıza servis ediyorum."),

r("Buyrun sipariş alın.",
  "Buyurun efendim, ne arzu edersiniz?",
  "Üç ayran, bir sütlaç.",
  "Elbette, 3 Yayık Ayran 135 TL ve Fırın Sütlaç 100 TL. Başka bir arzunuz var mı?",
  "Bir de köfte.",
  "Memnuniyetle, Izgara Köfte 240 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yok hepsi bu.",
  "Siparişinizi hemen iletiyorum, afiyet olsun."),

r("Sipariş alıyor musunuz?",
  "Evet efendim, buyurun ne arzu edersiniz?",
  "Bir tavuk salata.",
  "Tabii, Izgara Tavuk Salata 210 TL. Başka bir isteğiniz var mı?",
  "Bir de şalgam suyu ekle.",
  "Elbette, Şalgam Suyu 50 TL olarak eklendi. Eklemek istediğiniz bir şey var mı?",
  "Hayır hepsi bu.",
  "Kısa sürede masanıza getiriyorum efendim."),

r("Bize bakıyor musunuz?",
  "Evet efendim, buyurun. Ne arzu ederdiniz?",
  "İki köfte iki döner.",
  "Memnuniyetle, 2 Izgara Köfte 480 TL ve 2 Et Döner 560 TL. Başka bir arzunuz var mı?",
  "Dört ayran da ekleyelim.",
  "Tabii, 4 Yayık Ayran 180 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Yok teşekkürler.",
  "Hemen hazırlıyorum efendim."),

r("Afedersiniz, sipariş verebilir miyiz?",
  "Evet efendim, buyurun ne arzu edersiniz?",
  "Bir mercimek, bir döner.",
  "Elbette, Mercimek Çorbası 85 TL ve Et Döner 280 TL. Başka bir arzunuz var mı?",
  "Bir limonata da.",
  "Memnuniyetle, Limonata 70 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Hepsi bu kadar.",
  "Siparişinizi hızla hazırlatıyorum efendim."),

r("Müsaade ederseniz sipariş alsanız.",
  "Tabii efendim, buyurun ne arzu edersiniz?",
  "İki sütlaç.",
  "Memnuniyetle, 2 Fırın Sütlaç 200 TL. Başka bir isteğiniz var mı?",
  "Bir de mantar çorbası ekle.",
  "Elbette, Kremalı Mantar Çorbası 95 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Yok teşekkürler.",
  "Kısa sürede masanıza getiriyorum."),

r("Çorba ne kadar?",
  "Mercimek Çorbası 85 TL, Kremalı Mantar Çorbası 95 TL. Hangisini istersiniz?",
  "İki mantar çorbası.",
  "Tabii, 2 Kremalı Mantar Çorbası 190 TL. Başka bir isteğiniz var mı?",
  "Bir döner de.",
  "Memnuniyetle, Et Döner 280 TL olarak eklendi. Ekleyeceğimiz bir şey var mı?",
  "Hayır hepsi bu.",
  "Birazdan masanıza servis ediyorum efendim, afiyet olsun."),

r("Salata kaç TL?",
  "Izgara Tavuk Salata 210 TL. Arzu eder misiniz?",
  "Evet iki tane.",
  "Elbette, 2 Izgara Tavuk Salata 420 TL. Başka bir isteğiniz var mı?",
  "İki de limonata.",
  "Tabii, 2 Limonata 140 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yeterli teşekkürler.",
  "Hemen hazırlıyorum efendim."),

r("Şalgam ne kadar?",
  "Şalgam Suyu 50 TL. Siparişinize ekleyelim mi?",
  "İki şalgam.",
  "Memnuniyetle, 2 Şalgam Suyu 100 TL. Başka bir arzunuz var mı?",
  "Bir de künefe olsun.",
  "Elbette, Künefe 140 TL olarak eklendi. Başka bir isteğiniz var mı?",
  "Hepsi bu.",
  "Sıcak sıcak hemen masanıza getiriyorum."),

r("Kolay gelsin, ne hızlı çıkar?",
  "Çorbalarımız hızlı hazır olur, Mercimek veya Mantar ister misiniz?",
  "İki mercimek.",
  "Tabii, 2 Mercimek Çorbası 170 TL. Başka bir arzunuz var mı?",
  "İki de ayran ekle.",
  "Elbette, 2 Yayık Ayran 90 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Siparişinizi hemen iletiyorum efendim."),

r("İyi akşamlar, oturacağız.",
  "İyi akşamlar, hoş geldiniz efendim. Ne arzu edersiniz?",
  "Bir köfte bir sütlaç.",
  "Memnuniyetle, Izgara Köfte 240 TL ve Fırın Sütlaç 100 TL. Başka bir isteğiniz var mı?",
  "Bir de şalgam suyu.",
  "Tabii, Şalgam Suyu 50 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hayır yeterli.",
  "Birazdan masanıza getiriyorum, afiyet olsun."),

r("Merhaba, acıktık.",
  "Merhabalar, buyurun. Ne arzu edersiniz?",
  "Döner ve çorba.",
  "Elbette, Et Döner 280 TL. Mercimek mi Mantar Çorbası mı istersiniz?",
  "Mantar olsun.",
  "Tabii, Kremalı Mantar Çorbası 95 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hayır hepsi bu.",
  "Hemen hazırlıyorum, kısa sürede masanızda olacak."),

r("Akşamlar hayırlı olsun.",
  "Akşamlar hayırlı olsun efendim, hoş geldiniz. Ne arzu edersiniz?",
  "İki limonata, bir künefe.",
  "Memnuniyetle, 2 Limonata 140 TL ve Künefe 140 TL. Başka bir isteğiniz var mı?",
  "Bir de fırın sütlaç.",
  "Tabii, Fırın Sütlaç 100 TL olarak eklendi. İlaveten bir arzunuz olur mu?",
  "Yok teşekkürler.",
  "Sıcak sıcak hemen masanıza servis ediyorum."),

r("Affedersiniz, müsait misiniz?",
  "Evet efendim, buyurun ne arzu edersiniz?",
  "Üç köfte.",
  "Elbette, 3 Izgara Köfte 720 TL. Ekleyeceğimiz bir şey var mı?",
  "Üç de ayran.",
  "Memnuniyetle, 3 Yayık Ayran 135 TL olarak eklendi. Başka bir arzunuz var mı?",
  "Hepsi bu kadar.",
  "Hemen hazırlıyorum efendim, afiyet olsun."),

]

out = os.path.join(os.path.dirname(__file__), 'raw_cat4.jsonl')
with open(out, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')

print(f"Toplam: {len(records)} kayıt → {out}")
